# Generated by Django 4.0.5 on 2022-06-06 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0004_alter_picture_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='insta_app.follow'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
