# Generated by Django 4.0.5 on 2022-06-06 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0007_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insta_app.comment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
