# Generated by Django 4.0.5 on 2022-06-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0008_alter_comment_parent_comment_alter_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insta_app.picture'),
        ),
    ]
