# Generated by Django 4.0.5 on 2022-06-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0010_remove_picture_likes_remove_picture_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='insta_app.picture'),
        ),
    ]
