# Generated by Django 4.0.5 on 2022-06-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0013_alter_comment_options_picture_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='author',
            new_name='user',
        ),
    ]
