# Generated by Django 4.0.5 on 2022-06-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0014_remove_comment_user_comment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to='insta_app.profile'),
        ),
    ]
