# Generated by Django 4.0.5 on 2022-06-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0016_remove_comment_commentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
