# Generated by Django 4.0.5 on 2022-06-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0018_comment_commentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='hashtags',
        ),
    ]
